/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.soict.hust.k57.mmdb.view;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author thinhnt
 */
public class ResultImagePanel extends JPanel {

    private boolean selected = false;
    
    /**
     * Creates new form NewJPanel
     */
    public ResultImagePanel() {
        initComponents();
    }

    public void setImage(ImageIcon img) {
        img = prepareImgSize(img);
        imageLabel.setIcon(img);
    }
    
    public void setDistance(double d){
        distanceLabel.setText("Distance: " + d);
    }

    public void setImageName(String name) {
        imgNameLabel.setText(name);
    }

    private ImageIcon prepareImgSize(ImageIcon img) {
        Image image = img.getImage();
        int w = img.getIconWidth();
        int h = img.getIconHeight();
        image = image.getScaledInstance(w * 100 / h, 100, Image.SCALE_SMOOTH);
        return new ImageIcon(image);
    }

    public void enableSelectedEffect(){
        imageLabel.setBorder(BorderFactory.createLineBorder(Color.GREEN, 3));
        distanceLabel.setForeground(Color.GREEN);
        imgNameLabel.setForeground(Color.GREEN);
    }
    
    public void disableSelectedEffect(){
        imageLabel.setBorder(BorderFactory.createEmptyBorder());
        distanceLabel.setForeground(Color.BLACK);
        imgNameLabel.setForeground(Color.BLACK);
    }
    
    public boolean isEmpty(){
        return "".equals(imgNameLabel.getText());
    }
    
    public void setSelected(boolean selected){
        this.selected = selected;
    }
    
    public boolean isSelected(){
        return selected;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        imgNameLabel = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 109, 109)));

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(imgNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {distanceLabel, imageLabel, imgNameLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(distanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imgNameLabel;
    // End of variables declaration//GEN-END:variables
}
